apiVersion: v2
name: actualbudget
description: A local-first personal finance app
icon: https://raw.githubusercontent.com/actualbudget/docs/refs/heads/master/static/img/actual.png

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.5.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "25.4.0"

kubeVersion: ">=1.16.0-0"

home: https://actualbudget.org/

maintainers:
  - name: burakince
    email: burak.ince@linux.org.tr
    url: https://www.burakince.com

sources:
  - https://github.com/community-charts/helm-charts
  - https://github.com/actualbudget/actual

keywords:
  - docker
  - finance
  - personal-finance
  - money
  - budgeting

annotations:
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/community-charts/helm-charts
    - name: Upstream Project
      url: https://github.com/actualbudget/actual
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |
    - Add discoveryUrl to openid provider and deprecate dicovertUrl field
  artifacthub.io/images: |
    - name: actualbudget
      image: actualbudget/actual-server:25.4.0
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
  artifacthub.io/license: MIT
  artifacthub.io/maintainers: |
    - name: burakince
      email: burak.ince@linux.org.tr
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/screenshots: |
    - title: User Interface Overview
      url: https://raw.githubusercontent.com/actualbudget/docs/refs/heads/master/static/img/a-tour-of-actual/tour-overview-of-user-interface.png
    - title: Account Register Overview
      url: https://raw.githubusercontent.com/actualbudget/docs/refs/heads/master/static/img/a-tour-of-actual/tour-account-register-overview.png
    - title: Budget Overview
      url: https://raw.githubusercontent.com/actualbudget/docs/refs/heads/master/static/img/a-tour-of-actual/tour-budget-overview.png
    - title: Payees Overview
      url: https://raw.githubusercontent.com/actualbudget/docs/refs/heads/master/static/img/a-tour-of-actual/tour-payees-overview.png
    - title: Reports Overview
      url: https://raw.githubusercontent.com/actualbudget/docs/refs/heads/master/static/img/a-tour-of-actual/tour-reports-overview.png
    - title: Rules Overview
      url: https://raw.githubusercontent.com/actualbudget/docs/refs/heads/master/static/img/a-tour-of-actual/tour-rules-overview.png
    - title: Schedules Overview
      url: https://raw.githubusercontent.com/actualbudget/docs/refs/heads/master/static/img/a-tour-of-actual/tour-schedules-overview.png
  artifacthub.io/signKey: |
    fingerprint: 939B1A0ED8AAA8E722ACCDB3B6A012EE8A76426A
    url: https://keybase.io/communitycharts/pgp_keys.asc

dependencies: []
