# Test values file for MLFlow WITHOUT auth.existingDatabaseSecret (old insecure way)
auth:
  enabled: true
  adminUsername: "admin"
  adminPassword: "S3cr3+"
  postgres:
    enabled: true
    host: "postgresql--auth-instance1.abcdef1234.eu-central-1.rds.amazonaws.com"
    port: 5432
    database: "auth"
    # Hardcoded credentials (insecure)
    user: "mlflowauth"
    password: "A4m1nPa33w0rd!"

# Also configure backend store for comparison
backendStore:
  postgres:
    enabled: true
    host: "postgresql-instance1.cg034hpkmmjt.eu-central-1.rds.amazonaws.com"
    port: 5432
    database: "mlflow"
    # Using existing secret for backend (secure)
    user: ""
    password: ""
  existingDatabaseSecret:
    name: "postgres-database-secret"
    usernameKey: "username"
    passwordKey: "password"