{{- if and .Values.main.persistence.enabled (not .Values.main.persistence.existingClaim) (eq (int .Values.main.count) 1) }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "n8n-main.persistence.fullname" . }}
  labels:
    {{- include "n8n-main.persistence.labels" . | nindent 4 }}
  {{- with .Values.main.persistence.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.main.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.main.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.main.persistence.size }}
  {{- if .Values.main.persistence.storageClass }}
    {{- if (eq "-" .Values.main.persistence.storageClass) }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ .Values.main.persistence.storageClass | quote }}
    {{- end }}
  {{- end }}
{{- end }}
