apiVersion: v2
name: outline
description: A Helm chart for the fastest knowledge base for growing teams. Beautiful, realtime collaborative, feature packed, and markdown compatible.
icon: https://avatars.githubusercontent.com/u/1765001?s=200&v=4
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.6.5
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.87.4"
kubeVersion: ">=1.23.0-0"
home: https://www.getoutline.com/
maintainers:
  - name: burakince
    email: burak.ince@linux.org.tr
    url: https://www.burakince.com
sources:
  - https://github.com/community-charts/helm-charts
  - https://github.com/outline/outline/
keywords:
  - outline
  - knowledge base
  - knowledge
  - docs
  - documentation
  - collaboration
  - markdown
  - wiki
annotations:
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/community-charts/helm-charts
    - name: Chart Usage Page
      url: https://community-charts.github.io/docs/charts/outline/usage
    - name: Upstream Project
      url: https://github.com/outline/outline/
    - name: Official Usage Documentation
      url: https://docs.getoutline.com/s/guide
    - name: Official Hosting Documentation
      url: https://docs.getoutline.com/s/hosting/
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |-
    - kind: changed
      description: Update outlinewiki/outline image version to 0.87.4
      links:
        - name: Upstream Project
          url: https://hub.docker.com/r/outlinewiki/outline
  artifacthub.io/images: |
    - name: outline
      image: outlinewiki/outline:0.87.4
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
  artifacthub.io/license: Apache-2.0
  artifacthub.io/maintainers: |
    - name: burakince
      email: burak.ince@linux.org.tr
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/screenshots: |
    - title: Outline Home Page
      url: https://user-images.githubusercontent.com/380914/110356468-26374600-7fef-11eb-9f6a-f2cc2c8c6590.png
  artifacthub.io/signKey: |
    fingerprint: 939B1A0ED8AAA8E722ACCDB3B6A012EE8A76426A
    url: https://keybase.io/communitycharts/pgp_keys.asc
dependencies:
  - name: redis
    version: 22.0.7
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    version: 16.7.27
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: minio
    version: 5.4.0
    repository: https://charts.min.io/
    condition: minio.enabled
