suite: test drone kubernetes runner service
templates:
  - runner-service.yaml
tests:
  - it: should be empty if kube runner is not enabled
    set:
      kubeRunner.enabled: false
    asserts:
      - hasDocuments:
          count: 0

  - it: should match snapshot of default values
    set:
      kubeRunner.service.annotations:
        test-key: test-value
    chart:
      version: 1.0.0
      appVersion: 1.0.0
    asserts:
      - matchSnapshot: { }
