{{- if and .Values.backendStore.postgres.enabled .Values.backendStore.databaseMigration }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 900
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mlflow.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if and .Values.backendStore.postgres.dbChecker }}
      initContainers:
        - name: dbchecker
          image: "docker.io/busybox:1.32"
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              echo 'Waiting for Database to become ready...'
              until printf "." && nc -z -w 2 {{ required ".Values.backendStore.postgres.host is required if dbchecker is enabled!" .Values.backendStore.postgres.host }} {{ required ".Values.backendStore.postgres.port is required if dbchecker is enabled!" .Values.backendStore.postgres.port }}; do
                  sleep 2;
              done;
              echo 'Database OK ✓'
      {{- end }}
      containers:
        - name: postgres-migration-job
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ template "mlflow.fullname" . }}-env-configmap
            - secretRef:
                name: {{ template "mlflow.fullname" . }}-env-secret
          command: ["python"]
          args:
            - /opt/mlflow/migrations.py
          volumeMounts:
            - name: migrations-config
              mountPath: /opt/mlflow/migrations.py
              subPath: migrations.py
              readOnly: true
      volumes:
        - name: migrations-config
          configMap:
            name: {{ template "mlflow.fullname" . }}-migrations
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
{{- end }}