{{- if and .Values.oidcAuth.enabled .Values.oidcAuth.database.postgres.enabled (eq .Values.oidcAuth.database.postgres.existingSecret.name "") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.fullname" . }}-oidc-auth-db-secret
  labels:
    app: {{ include "mlflow.name" . }}
    chart: {{ include "mlflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  username: {{ required "oidcAuth.database.postgres.user must be specified" .Values.oidcAuth.database.postgres.user | b64enc }}
  password: {{ required "oidcAuth.database.postgres.password must be specified" .Values.oidcAuth.database.postgres.password | b64enc }}
{{- end }}
