log:
  level: info

db:
  type: postgresdb

worker:
  mode: queue
  count: 1

  waitMainNodeReady:
    enabled: true

  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 20
    failureThreshold: 5

  readinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 20
    failureThreshold: 5

webhook:
  mode: queue
  count: 1

  waitMainNodeReady:
    enabled: true

  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 20
    failureThreshold: 5

  readinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 20
    failureThreshold: 5

redis:
  enabled: true

postgresql:
  enabled: true
  primary:
    persistence:
      enabled: false
