{{- if .Values.kubeRunner.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "drone.runnerFullname" . }}
  labels:
    {{- include "drone.runnerLabels" . | nindent 4 }}
  {{- with .Values.kubeRunner.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.kubeRunner.service.type }}
  ports:
    - port: {{ .Values.kubeRunner.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "drone.runnerSelectorLabels" . | nindent 4 }}
{{- end }}