apiVersion: v1
kind: Service
metadata:
  name: {{ include "drone.serverFullname" . }}
  labels:
    {{- include "drone.serverLabels" . | nindent 4 }}
  {{- with .Values.server.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "drone.serverSelectorLabels" . | nindent 4 }}
