suite: test job

templates:
  - job.yaml

tests:
  - it: should be empty when postgres or databaseMigration is not enabled
    asserts:
      - hasDocuments:
          count: 0

  - it: should have migration job when postgres and databaseMigration are enabled
    set:
      backendStore.postgres.enabled: true
      backendStore.postgres.host: postgres-service
      backendStore.postgres.port: 5432
      backendStore.postgres.database: postgres
      backendStore.databaseMigration: true
    asserts:
      - hasDocuments:
          count: 1
      - isKind:
          of: Job
      - isAPIVersion:
          of: batch/v1
  
  - it: should have dbchecker init container if enabled
    set:
      backendStore:
        databaseMigration: true
        postgres:
          enabled: true
          host: test-host
          database: test-database
          user: test-user
          password: test-password
          dbChecker: true
    asserts:
      - hasDocuments:
          count: 1
      - isKind:
          of: Job
      - equal:
          path: spec.template.spec.initContainers[0].name
          value: dbchecker
