{{- if or (eq .Values.tunnelSecrets.existingPemFileSecret.name "") (eq .Values.tunnelSecrets.existingConfigJsonFileSecret.name "") }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: tunnel-credentials
data:
  {{- if eq .Values.tunnelSecrets.existingConfigJsonFileSecret.name "" }}
  credentials.json: {{ required "Base64 encoded config file string is required! Run base64 -b 0 -i ~/.cloudflared/*.json and add output to tunnelSecrets.base64EncodedConfigJsonFile in values.yaml file." .Values.tunnelSecrets.base64EncodedConfigJsonFile | quote }}
  {{- end }}
  {{- if eq .Values.tunnelSecrets.existingPemFileSecret.name "" }}
  cert.pem: {{ required "Base64 encoded certificate pem file string is required! Run base64 -b 0 -i ~/.cloudflared/cert.pem and add output to tunnelSecrets.base64EncodedPemFile in values.yaml file." .Values.tunnelSecrets.base64EncodedPemFile | quote }}
  {{- end }}
{{- end }}
