name: Release Charts

on:
  push:
    branches: [ main ]
    paths:
      - 'charts/**'

  pull_request:
    branches: [ main ]
    paths:
      - 'charts/**'

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3.0
        with:
          version: v3.8.1

      - uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      - name: Add dependency chart repos
        run: |
          helm repo add jetstack https://charts.jetstack.io
          helm repo add community-charts https://community-charts.github.io/helm-charts

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          ## If executed with debug this won't work anymore.
          changed=$(ct --config ./.github/configs/ct-lint.yaml list-changed)
          charts=$(echo "$changed" | tr '\n' ' ' | xargs)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
            echo "::set-output name=changed_charts::$charts"
          fi

      - name: Run Artifact Hub lint
        run: |
          curl -s https://api.github.com/repos/artifacthub/hub/releases/latest | grep -E 'browser_download_url' | grep linux_amd64 | grep -Eo 'https://[^\"]*' | xargs wget -O - | tar -xz
          ./ah lint -p charts/mlflow || exit 1
          ./ah lint -p charts/drone || exit 1
          rm -f ./ah

      # - name: install helm unittest plugin
      #   if: steps.list-changed.outputs.changed == 'true'
      #   run: |
      #     helm env
      #     helm plugin install https://github.com/quintush/helm-unittest.git --version 0.2.8

      - name: Run chart-testing (lint)
        run: ct lint --debug --config ./.github/configs/ct-lint.yaml --lint-conf ./.github/configs/lintconf.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.3.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install --config ./.github/configs/ct-lint.yaml
        if: steps.list-changed.outputs.changed == 'true'

  release:
    needs: lint-test

    runs-on: ubuntu-latest

    if: ${{ github.event_name != 'pull_request' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3.0
        with:
          version: v3.8.1

      - name: Add dependency chart repos
        run: |
          helm repo add jetstack https://charts.jetstack.io
          helm repo add community-charts https://community-charts.github.io/helm-charts

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
