on:
  push:
    branches:
      - 'main'
    paths:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create a new file for update
        run: |
          cp -f README.md ${{ runner.temp }}/README.md

      - uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Update gh-pages branch with new file
        run: |
          cp -f ${{ runner.temp }}/README.md .
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add README.md
          git commit --signoff -m "Sync README from main"
          git push
